<?php

add_action( 'init', function() {
	register_post_type( 'team', array(
		'labels' => array(
			'name' => 'Team',
			'singular_name' => 'Team',
			'menu_name' => 'Team',
			'all_items' => 'All Team',
			'edit_item' => 'Edit Team',
			'view_item' => 'View Team',
			'view_items' => 'View Team',
			'add_new_item' => 'Add New Team',
			'new_item' => 'New Team',
			'parent_item_colon' => 'Parent Team:',
			'search_items' => 'Search Team',
			'not_found' => 'No team found',
			'not_found_in_trash' => 'No team found in Trash',
			'archives' => 'Team Archives',
			'attributes' => 'Team Attributes',
			'insert_into_item' => 'Insert into team',
			'uploaded_to_this_item' => 'Uploaded to this team',
			'filter_items_list' => 'Filter team list',
			'filter_by_date' => 'Filter team by date',
			'items_list_navigation' => 'Team list navigation',
			'items_list' => 'Team list',
			'item_published' => 'Team published.',
			'item_published_privately' => 'Team published privately.',
			'item_reverted_to_draft' => 'Team reverted to draft.',
			'item_scheduled' => 'Team scheduled.',
			'item_updated' => 'Team updated.',
			'item_link' => 'Team Link',
			'item_link_description' => 'A link to a team.',
		),
		'public' => true,
		'show_in_rest' => true,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
		),
		'delete_with_user' => false,
	) );

	register_post_type( 'press', array(
		'labels' => array(
			'name' => 'Press',
			'singular_name' => 'Press',
			'menu_name' => 'Press',
			'all_items' => 'All Press',
			'edit_item' => 'Edit Press',
			'view_item' => 'View Press',
			'view_items' => 'View Press',
			'add_new_item' => 'Add New Press',
			'new_item' => 'New Press',
			'parent_item_colon' => 'Parent Press:',
			'search_items' => 'Search Press',
			'not_found' => 'No press found',
			'not_found_in_trash' => 'No press found in Trash',
			'archives' => 'Press Archives',
			'attributes' => 'Press Attributes',
			'insert_into_item' => 'Insert into press',
			'uploaded_to_this_item' => 'Uploaded to this press',
			'filter_items_list' => 'Filter press list',
			'filter_by_date' => 'Filter press by date',
			'items_list_navigation' => 'Press list navigation',
			'items_list' => 'Press list',
			'item_published' => 'Press published.',
			'item_published_privately' => 'Press published privately.',
			'item_reverted_to_draft' => 'Press reverted to draft.',
			'item_scheduled' => 'Press scheduled.',
			'item_updated' => 'Press updated.',
			'item_link' => 'Press Link',
			'item_link_description' => 'A link to a press.',
		),
		'public' => true,
		'show_in_rest' => true,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
		),
		'delete_with_user' => false,
	) );

	register_post_type( 'work', array(
		'labels' => array(
			'name' => 'Portfolio',
			'singular_name' => 'Portfolio',
			'menu_name' => 'Portfolios',
			'all_items' => 'All Portfolios',
			'edit_item' => 'Edit Portfolio',
			'view_item' => 'View Portfolio',
			'view_items' => 'View Portfolios',
			'add_new_item' => 'Add New Portfolio',
			'new_item' => 'New Portfolio',
			'parent_item_colon' => 'Parent Portfolio:',
			'search_items' => 'Search Portfolios',
			'not_found' => 'No portfolios found',
			'not_found_in_trash' => 'No portfolios found in Trash',
			'archives' => 'Portfolio Archives',
			'attributes' => 'Portfolio Attributes',
			'insert_into_item' => 'Insert into portfolio',
			'uploaded_to_this_item' => 'Uploaded to this portfolio',
			'filter_items_list' => 'Filter portfolios list',
			'filter_by_date' => 'Filter portfolios by date',
			'items_list_navigation' => 'Portfolios list navigation',
			'items_list' => 'Portfolios list',
			'item_published' => 'Portfolio published.',
			'item_published_privately' => 'Portfolio published privately.',
			'item_reverted_to_draft' => 'Portfolio reverted to draft.',
			'item_scheduled' => 'Portfolio scheduled.',
			'item_updated' => 'Portfolio updated.',
			'item_link' => 'Portfolio Link',
			'item_link_description' => 'A link to a portfolio.',
		),
		'public' => true,
		'show_in_rest' => true,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
		),
		'rewrite' => array(
			'slug' => 'portfolio',
		),
		'delete_with_user' => false,
	) );
} );



?>